# Generated by Django 6.0 on 2026-01-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="measurement_data",
            field=models.JSONField(
                blank=True, help_text="Admin: Optional typed measurements", null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="measurement_photo",
            field=models.ImageField(
                blank=True,
                help_text="Admin: Upload photo of handwritten measurements",
                null=True,
                upload_to="measurements/%Y/%m/",
            ),
        ),
    ]
