# Generated by Django 6.0 on 2026-01-02 09:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_measurement_data_booking_measurement_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="measurement_photo",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Admin: Upload photo of handwritten measurements",
                max_length=255,
                null=True,
                verbose_name="measurement_photos",
            ),
        ),
    ]
