# Generated by Django 6.0 on 2026-01-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="URL of product image at time of order",
                max_length=500,
                null=True,
            ),
        ),
    ]
