# Generated by Django 6.0 on 2025-12-31 08:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("rent_per_day", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expected_return_date", models.DateField()),
                ("actual_return_date", models.DateField(blank=True, null=True)),
                ("actual_days_used", models.PositiveIntegerField(default=0)),
                (
                    "condition_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CLEAN", "Clean"),
                            ("DIRTY", "Dirty"),
                            ("DAMAGED", "Damaged"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "late_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "damage_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "rent_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RETURNED", "Returned"),
                            ("CLOSED", "Closed"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_transaction",
                        to="orders.orderitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rental Transaction",
                "verbose_name_plural": "Rental Transactions",
                "db_table": "rental_transactions",
            },
        ),
    ]
