# Generated by Django 6.0 on 2025-12-31 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FABRIC", "Fabric"),
                            ("READYMADE", "Ready Made"),
                            ("TRADITIONAL", "Traditional"),
                            ("ACCESSORY", "Accessory"),
                            ("INNERWEAR", "Innerwear"),
                        ],
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                (
                    "is_buyable",
                    models.BooleanField(
                        default=True, help_text="Can customers buy this product?"
                    ),
                ),
                (
                    "is_rentable",
                    models.BooleanField(
                        default=False, help_text="Can customers rent this product?"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StitchType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Shirt, Pant, Kurta", max_length=50, unique=True
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Stitch Type",
                "verbose_name_plural": "Stitch Types",
                "db_table": "stitch_types",
            },
        ),
        migrations.CreateModel(
            name="Fabric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fabric_category",
                    models.CharField(
                        choices=[("SHIRT", "Shirt Fabric"), ("PANT", "Pant Fabric")],
                        max_length=10,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("COTTON", "Cotton"),
                            ("LINEN", "Linen"),
                            ("POLYESTER", "Polyester"),
                            ("BLEND", "Blend"),
                            ("SILK", "Silk"),
                            ("WOOL", "Wool"),
                        ],
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(max_length=30)),
                (
                    "price_per_meter",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fabric_details",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fabric",
                "verbose_name_plural": "Fabrics",
                "db_table": "fabrics",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/%Y/%m/")),
                (
                    "is_primary",
                    models.BooleanField(default=False, help_text="Main display image"),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "db_table": "product_images",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="RentalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Full product value paid as deposit",
                        max_digits=10,
                    ),
                ),
                ("rent_per_day", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_config",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rental Configuration",
                "verbose_name_plural": "Rental Configurations",
                "db_table": "rental_configs",
            },
        ),
        migrations.CreateModel(
            name="TraditionalBoxItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="e.g., Kurta, Dhoti, Angavastram", max_length=100
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "is_stitchable",
                    models.BooleanField(
                        default=False, help_text="Can this item be stitched?"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="box_items",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Traditional Box Item",
                "verbose_name_plural": "Traditional Box Items",
                "db_table": "traditional_box_items",
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Stock Keeping Unit", max_length=100, unique=True
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("XS", "Extra Small"),
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                            ("XXL", "Double XL"),
                            ("XXXL", "Triple XL"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("color", models.CharField(max_length=30)),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank to use product's base price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variant",
                "verbose_name_plural": "Product Variants",
                "db_table": "product_variants",
                "unique_together": {("product", "size", "color")},
            },
        ),
    ]
